export const med_lst = [
  "How are you today?",
  "Did you have any trouble getting here?",
  "How do you like the weather?",
  "It’s quite hot/cold/snowy/rainy/windy, isn’t it?",
  "Did you have any trouble finding a place to park?",
  "How do you like [our city]? Have you ever visited before?",
  "Was there a lot of traffic on your way?",
  "How do you like living in [your city]?",
  "What do you prefer to be called?",
  "How has your visit with us been so far?",
  "Tell me about yourself.",
  "What brings you here today?",
  "Tell me something that's not in your application.",
  "What was your childhood like?",
  "What is your relationship with your family?",
  "Tell me about your family/upbringing.",
  "What else do you want us to know about you before you leave today?",
  "What is one question you wish we had asked you? Answer it.",
  "Is there anything else you would like me to know?",
  "Describe your personality.",
  "Describe your childhood and present living conditions.",
  "Tell me about your family. How do they feel about your decision to attend medical school?",
  "How would you describe yourself?",
  "What have you been doing since graduation?",
  "How do you think your parents feel about your accomplishments?",
  "Are your siblings as self motivated as you?",
  "Why do you want to be a doctor?",
  "When did you first become interested in medicine?",
  "What led you to pursue a career in medicine?",
  "What stimulated your interest in medicine?",
  "Name a meaningful experience you’ve had and how it has shaped you to pursue work as a physician.",
  "What major influences in your life led to your decision to pursue medicine?",
  "What has been your path to medicine?",
  "Did you have an “aha” moment when you decided medicine was the career for you?",
  "Why do you want to be a doctor and not a PA, NP, RN?",
  "There are no doctors in your family. How do you know medicine is the right profession for you?",
  "Has anyone ever attempted to dissuade you from being a physician? If so, how did you respond?",
  "If you want to help people, why not social work?",
  "What do you feel is the purpose of Medical School?",
  "What do you intend to gain from a medical education?",
  "What excites you about medicine in general?",
  "Tell me about your undergraduate university and why you chose to go there.",
  "Describe your undergraduate education.",
  "How did you like your undergraduate university?",
  "If you could change one thing about your undergraduate university, what would it be?",
  "Which of your college courses interested you the most?",
  "What was your favorite course in college and why?",
  "What was your least favorite course in college and why?",
  "What was your most difficult course in college?",
  "If you could start your college career all over again, what would you do differently?",
  "In what course did you get the worst grades? Why?",
  "Why did you choose your undergraduate major?",
  "What class impressed you positively or negatively during your undergraduate education?",
  "Do you feel your undergraduate education has challenged you?",
  "What is your greatest academic achievement?",
  "Are you a crammer or do you study a little bit each day?",
  "In what environment do you learn best?",
  "What was something you learned for fun?",
  "Tell me about your study habits.",
  "Tell me about the major challenges you’ve faced in your college career.",
  "Who was the best teacher you have had and why?",
  "Tell me about your research.",
  "What research have you done and why?",
  "What is the most impactful research you have done?",
  "Pretend you are at a conference presenting your most important research and I am in the audience. Give me your presentation.",
  "Do you expect to continue research in medical school?",
  "What labs or research institutions at our school particularly interest you?",
  "Tell me about your publication.",
  "Why are you pursuing medicine and not research?",
  "If you were given a $1 million grant to perform research, what would you do with it?",
  "How can you balance research and clinical experience?",
  "How have you contributed to your community?",
  "What volunteer experiences have you had?",
  "How will you keep in touch with community needs?",
  "What experiences have you had in community involvement that demonstrate your commitment to medicine?",
  "What was your most meaningful community service experience?",
  "Do you think your volunteer work makes a real difference?",
  "Describe a specific time you helped someone in the last two weeks.",
  "Is medicine a service profession?",
  "Tell me about a time when you put your needs aside to help a classmate or coworker understand a task. How did you help him or her? What was the result?",
  "To what extent do you feel that you owe a debt to your fellow man? To what extent do you owe a debt to those less fortunate than yourself? Please explain.",
  "What do you do for fun?",
  "What do/did you spend most of your time doing outside of the classroom?",
  "Tell me about your most meaningful extracurricular experience.",
  "What are your hobbies?",
  "Pretend you have been working and studying nonstop for weeks and finally have a day off. What do you do with it?",
  "Are you involved in the arts in any way?",
  "Are you involved in sports?",
  "What do you do for exercise?",
  "Tell me about your [extracurricular] experience.",
  "What extracurricular activities have you been involved in?",
  "Tell me specifically what do you in [activity]?",
  "What are your interests outside of medicine?",
  "Tell me about [experience], why you chose to participate, and how that affected your decision to pursue medicine.",
  "How have you explored medicine as a career?",
  "Which clinical experience did you find most impactful?",
  "What was your most memorable physician shadowing experience?",
  "Tell me the most interesting case you have seen.",
  "Tell me about an experience during your shadowing that made you uncomfortable.",
  "Describe a time when you were a patient and received medical care. What did you learn from that experience?",
  "Is medicine a rewarding career? Why?",
  "What health care experiences have you had?",
  "What clinical/hospital experiences have you had?",
  "Do you know what a real doctor’s life is like?",
  "What steps have you taken to acquaint yourself with what a physician does?",
  "How do you handle blood and gore?",
  "Why do you think so many people want to be doctors?",
  "Describe a patient who left a mark. Who was your most/least favorite patient?",
  "How do you know you will enjoy taking care of sick people?",
  "Have you ever seen someone die? How did you handle it?",
  "What are some of the risks of going into private practice versus working in a collaborative setting?",
  "If you could go back and improve one area of your application, what would it be and why?",
  "Do you think the MCAT is a good measure or determining factor for admission to medical school?",
  "If you are not accepted to medical school this year, what will you do?",
  "What other schools have you applied to?",
  "Where else have you interviewed?",
  "How do you plan to finance your medical education?",
  "What happened during the MCAT?",
  "Where do you see yourself in 10-15 years?",
  "What type of doctor would you like to be?",
  "What speciality interests you?",
  "What are your specific goals in medicine?",
  "Where do you plan to practice after you graduate?",
  "What are your career plans and what led you to these decisions?",
  "Would you like academic medicine as a career?",
  "What impact do you want to have on the medical profession?",
  "Do you prefer the idea of basic research or of working with people?",
  "Would you practice in the inner city? What do you think happens to people who practice medicine there (attitude changes, etc.)?",
  "In 25 years, when you look back on your medical career, how will you determine if you have been successful?",
  "Do you have an alternative career plan?",
  "What sort of relationship, long-term or short-term, would you like with your patients?",
  "Take me through a perfect day in your life ten years from now.",
  "How will you add to the diversity of this school?",
  "What does diversity mean to you?",
  "Describe a time you were in the minority.",
  "What values do you bring from your cultural background that will be useful in medicine?",
  "At [school], we work with underserved populations such as Hispanics and African Americans. Have you had experience with underserved populations?",
  "What experiences have you had working with diverse populations?",
  "Describe any travels that you have undertaken and exposure to other cultures than your own, if any.",
  "Describe a situation in which you have worked with a diverse group of people. What did you learn from that situation?",
  "How do you think your personal background will affect your practice?",
  "How might you best meet the needs of a multiethnic, multicultural patient population?",
  "How do you handle stress?",
  "What causes you the most stress in your life?",
  "Medicine is a depressing business - how will you cope?",
  "How will you handle the stress of medical school?",
  "What things frustrate you the most? How do you usually cope with them?",
  "How do you normally handle and relieve stress?",
  "What scares you most about medical school?",
  "What do you do to blow off steam?",
  "What do you think you will struggle with during medical school?",
  "From what you understand of medical school, what part of the program will be most difficult for you?",
  "How do you handle failure?",
  "How do you handle change?",
  "How would you handle being unable to help someone or making a serious clinical mistake?",
  "How will you deal with leaving your family and moving to a new location?",
  "Have you ever been overwhelmed? How did you handle it?",
  "How might you deal with a terminally ill patient?",
  "When you need counseling for personal problems, whom do you talk with?",
  "Tell me about a time when you worked effectively under a great deal of pressure.",
  "Tell me about a particularly stressful situation you encountered in college and how you handled it.",
  "What has been the highest pressure situation you’ve been under in recent years? How did you cope with it?",
  "Describe a situation that required a number of things to be done at the same time. How did you handle it? What was the result?",
  "The night before your final exam, your father has a heart-attack and is admitted to a hospital, what do you do?",
  "What does professionalism mean to you?",
  "Describe the ideal physician.",
  "What qualities do you look for in a physician?",
  "How do you think your role as a physician fits in with your role as a member of the community?",
  "What is the role of a physician in the community?",
  "What makes a good physician?",
  "Tell me about a time you saw someone acting unprofessionally. What did you do and why?",
  "In an operating room, there is the surgeon, anesthesiologist, nurses, techs, etc. Who is the most important person in this room?",
  "If a doctor is the coach of a sport, what sport do you think would fit best and why?",
  "What do you think are the most important qualities a person must have to be a good doctor? How do you rate yourself in these areas?",
  "Tell me about a time when you witnessed unprofessional or unethical behavior on the part of a classmate. How did you handle it?",
  "Describe an ethical dilemma you have you encountered.",
  "What do you feel are the social responsibilities of a physician?",
  "What is your concept of the doctor/patient relationship?",
  "What is your concept of the biopsychosocial model of medicine?",
  "What are your strengths?",
  "What are your weaknesses?",
  "Name some good qualities you possess and one you would like to work on or change.",
  "Name five words off the top of your head that describe you.",
  "If your best friends were asked to describe you, what would they say?",
  "Think about someone who doesn’t like you. What would they say about you?",
  "Think about people you don’t like. What don’t you like about them?",
  "How would your teammates describe you?",
  "How would your professors describe you?",
  "If we contacted your references now, what do you think they would say about you?",
  "What is your weakness that concerns you the most?",
  "If you could change one aspect of your personality with a snap of your fingers, what would you change?",
  "What are you doing now to better yourself?",
  "What qualities do you possess that would make you a good doctor?",
  "Why would you make a good physician?",
  "What aspects of your life’s experiences do you think make you a good candidate for medical school?",
  "What are your positive qualities?",
  "What has been your most defining moment?",
  "Provide me with an example of your leadership ability.",
  "What leadership positions have you held?",
  "Do you like to work alone or with other people?",
  "What have you done that shows initiative?",
  "What are you most proud of about yourself?",
  "What is your greatest accomplishment?",
  "What were your most memorable accomplishments in your college career?",
  "How do you manage your time?",
  "What drives you?",
  "Rate your humbleness on a scale of 1-10.",
  "What is the difference between a talent and a skill?",
  "Define success.",
  "Define empathy and give an example.",
  "Define maturity.",
  "What are you most proud of that is not on your resume?",
  "Name one situation that has impacted you the most.",
  "What is your passion?",
  "What do you love?",
  "What makes you laugh?",
  "What makes you angry?",
  "What makes you frustrated?",
  "Do you have any biases?",
  "Would you rather be a compassionate or caring doctor?",
  "What things give you the greatest satisfaction in your life?",
  "Tell me about a time when you became really angry over a situation in college.",
  "Give me an example of a time when you’ve motivated others.",
  "Give me an example of when you showed initiative and took the lead.",
  "Tell us about a time where you had to be a leader.",
  "Tell us about a time you were a member of a team.",
  "How do you go about making important decisions?",
  "How do you work in a team?",
  "How have you changed since freshman year of college?",
  "What is the biggest mistake you have ever made and what have you learned from it?",
  "Do you feel you have had to overcome any hardships or struggles?",
  "What are you most ashamed of?",
  "What is your biggest regret in life?",
  "What is your best memory?",
  "What is your worst memory?",
  "What are the best and worst things that have ever happened to you?",
  "Describe a time you have failed at something in a non-academic setting.",
  "What was a time you made a poor choice?",
  "Tell me about a time when you faced a conflict or anger with another individual.",
  "Tell me about a time when you were criticized unfairly.",
  "Describe a time you let someone down and how you resolved the situation.",
  "Describe a personal conflict you had with someone and how you dealt with it.",
  "If you could go back and relive one day in your life, what day would that be? Would you change something about it? If so, what?",
  "Tell me about the lowest point in your life.",
  "What is the worst thing that has ever happened to you?",
  "How do you work with a teammate who is not pulling their weight?",
  "Give me an example of a time when you were on a team and it didn’t work out. What would you do differently?",
  "When were you glad you gave someone a second chance?",
  "Tell me about a time you felt misjudged by someone and how you responded to the situation.",
  "Describe a time you misjudged someone.",
  "Have you ever been discriminated against?",
  "When was the last time you felt humbled?",
  "Have you ever harmed someone?",
  "Describe a time you needed to ask for help.",
  "Tell me about a time you had to assert yourself.",
  "What challenges do you expect to encounter as a physician?",
  "What is the hardest question you have ever been asked? How did you answer it?",
  "What personal challenges do you think you'll face as a physician?",
  "What are some of the challenges you foresee in your career?",
  "What is the biggest challenge you’ve overcome in your life?",
  "Can you tell me about a significant challenge you had to overcome? How did you handle it?",
  "Tell me about a time when you handled a stressful situation poorly.",
  "Tell me about a difficult decision you’ve made in the past year.",
  "Describe a situation in which you were dependable or demonstrated initiative. One in which you were not as dependable as you would have liked.",
  "Tell me about a time when you were forced to make an unpopular decision.",
  "Tell me about a time where you experienced conflict with a colleague.",
  "Tell me about a time when you were disappointed in your performance.",
  "Tell me about a situation in which you overcame adversity.",
  "Describe a situation in which you had to break someone’s confidence.",
  "Tell me about a time when you had to build rapport quickly with someone under difficult conditions.",
  "Tell me about a problem you had with a classmate or professor. How did you handle it?",
  "Tell me about a time when others working with you disagreed with your ideas. How did you handle it?",
  "Describe a situation in which your performance did not meet your professor’s or supervisor’s expectations. What happened? How did you handle the situation?",
  "Tell me about a time when you successfully handled another person when that person didn’t particularly like you.",
  "Tell me about a time when you had a difficult communication problem.",
  "Tell me about a time when you were able to successfully work with another person, even when you did not like them personally.",
  "Tell me about a time when you had to go above and beyond the call of duty in order to get the job done.",
  "Tell me about a time when you’ve been disappointed in a teammate or fellow group member. What happened? How did you approach the situation?",
  "Tell me about a time when you made a mistake and what you did to fix it?",
  "Describe your style of communicating and interacting with others. Give an example of a situation in which you had to utilize effective interpersonal skills.",
  "Describe how you can effectively deal with someone in crisis.",
  "Give an example of a time you changed your position on a topic. Why?",
  "If you could cure a disease, what would it be and why?",
  "Discuss a time when you went against the orders of your superiors.",
  "Why our school?",
  "Tell me about why you are interested in this program.",
  "What qualities are you looking for in a medical school?",
  "Describe your ideal medical school.",
  "What interests you most about our school?",
  "What attracts you to our school particularly?",
  "Tell me what you know about our school.",
  "Why do you want to be a student here?",
  "What two or three things are important to you in a medical school?",
  "What attracted you to this program?",
  "Tell us your opinion of this medical school's curriculum.",
  "Where do we stand in your list of medical school preferences?",
  "What are you looking for in a medical school? How will you decide which medical school to choose?",
  "Why not go to your state school where tuition is cheaper?",
  "If you were accepted to all the schools you applied to, how would you decide where to attend?",
  "If you got into Harvard or Stanford, why would you come here?",
  "What is your top choice medical school?",
  "If our school was theoretically your top choice school, what would be your second choice?",
  "If I offered you a spot in our next class before you left this interview, would you accept?",
  "How do you think you did in this interview?",
  "What opportunities/activities would you take part in if you were a student here?",
  "Why should we choose you?",
  "What do you have to offer our school?",
  "What contributions can you make to our school?",
  "What do you have to offer that others don’t?",
  "What will you contribute to the profession?",
  "What makes you think you are as qualified as applicants with more experience than you?",
  "What sets you apart from the rest of the applicants that are interviewing here?",
  "What do you hope to bring to our medical school?",
  "There are 1,000 applicants as qualified as you. Why should we pick you?",
  "What would you like written in your obituary?",
  "What do you want me to say about you to the admissions board?",
  "How will you change the world?",
  "Imagine you are on trial and we are the jury. Try to convince use you are compassionate and empathetic.",
  "If you were a cookie (animal/book/dessert/utensil/car/etc), what cookie would you be?",
  "If you could be any character in history, who would you be? Why?",
  "If you could invite four people to dinner, who would they be? Why?",
  "Of all the people, dead or alive, who would you most like to have dinner with and why?",
  "Who would you say has been the most influential person in the last one-hundred years?",
  "Tell me about a book you read recently. Why does it interest you? Why did you select that book?",
  "Tell me about a movie you recently saw.",
  "Who is your hero/idol/inspiration? Why?",
  "What newspapers, journals, etc., do you read on a regular basis?",
  "What TV character is most like your personality?",
  "If you walked into a room with a block of stone and a chisel and were asked to carve any idea or concept, what would you carve and why?",
  "If you were given $1 million, what would you do with it?",
  "What is your favorite color?",
  "If the military draft were reactivated and you were drafted tomorrow, what would you do?",
  "What is your favorite book (magazine/movie/TV show/etc) and why?",
  "Tell me about a book that changed your perspective on life.",
  "I work for Time Magazine and am in charge of selecting Person of the Year. Who do you nominate and why?",
  "Who has been a mentor in your life?",
  "Tell me a joke.",
  "Tell me a funny story.",
  "What is the meaning of life?",
  "What is the best advice you have been given?",
  "What is an interesting fact you know?",
  "Explain to a six year old how to tie shoes without using hand gestures.",
  "Define pain without examples to a six year old.",
  "How would you teach someone who doesn’t speak English to use a toothbrush?",
  "I am visiting your state/school for the first time. Where would you take me?",
  "Name five things you can do with a pencil besides draw and write.",
  "My house is infested with chipmunks. What do I do?",
  "Do you ever think about your own mortality?",
  "What kind of medical problems will we face on Mars?",
  "What is the biggest problem in the world today?",
  "What is your solution to terrorism?",
  "What do you think about the ongoing conflict in Iraq?",
  "If you could change one thing about the future what would it be?",
  "What are your thoughts on [current event]?",
  "Create a reality show where the winner gets a full ride to medical school.",
  "If you were the head of Company X and we gave you $100 billion, how would you allocate the money?",
  "If you could be granted three wishes for making the world/society/your community a better place, what would they be and why?",
  "If you could be any type of cell in the human body, which type of cell would you choose and why?",
  "What is the most important event that has occurred to you in the last five years?",
  "If I gave you $40,000 to start a business, what would you start?",
  "What are some of the challenges in medicine today?",
  "What do you think about the changes that are taking place in medicine today?",
  "What do you think is the most pressing issue in medicine today?",
  "What do you think about our healthcare system and the way it should go?",
  "What do you think is wrong with the current healthcare system?",
  "What problems do you see in healthcare now and in the next ten years?",
  "What would you do to remedy healthcare in the United States?",
  "Why do you think many physicians are unhappy practicing medicine?",
  "What do you think contributes to physician burnout and the high rates of depression/suicide in this profession?",
  "What is the greatest problem facing healthcare today, and how would you solve it?",
  "What do you think about American primary health care delivery (i.e., status quo, total private systems, national health insurance)?",
  "What are the differences between Britain's health care delivery system and ours?",
  "Discuss National Health Insurance and how it would affect the physician and the patient.",
  "What are the negative aspects of medicine from a professional standpoint?",
  "How would your plans differ if you knew that all physicians would be working in HMO’s in the future?",
  "What do you think about HMO’s and the changes taking place in medicine?",
  "Do mid-level providers with PhDs have the right to call themselves “Doctor” in a clinical setting?",
  "If an alien were to land here on Earth and ask you to describe how our healthcare system currently works, what would you say?",
  "Where do you see the state of healthcare in the next 10 years?",
  "If you could change one thing about the Affordable Care Act, what would it be?",
  "What are three positives and three negatives about the Affordable Care Act.",
  "What does Obamacare mean?",
  "What do you think about a public option for health insurance?",
  "What do you think about health insurance mandates?",
  "Do you think we should have universal healthcare?",
  "If you were president, what would your health reform bill look like?",
  "What do you think accounts for the high cost of healthcare?",
  "If the president approached you to help solve a local obesity problem, how would you go about making a difference in your community?",
  "Can you think of any examples in our society when healthcare is a right?",
  "When is healthcare a privilege? When is it not clear?",
  "How would you recommend alleviating the shortage of primary care physicians in certain areas of the US?",
  "What do you think are the three most pressing public health issues facing the US today?",
  "How can we work to reduce discrepancies in healthcare delivery in different areas of the city/state/country?",
  "What are your thoughts on alternative medicine?",
  "What technology do you think will have the biggest impact on healthcare in the next 10 years?",
  "What do you think will be the next major global medical breakthrough?",
  "Do you think that doctors are being paid too much or too little? Why?",
  "How do you treat mid-level providers in a healthcare team? How important are they?",
  "What do you think is one of the biggest challenges with EMR physicians face? What do you think the younger, tech-savvy generation will do to change this?",
  "How do you feel about euthanasia?",
  "A patient who has been in an accident needs a blood transfusion. She states that her religion does not allow them. You are the physician in charge. What will you do? Will you override her strong objection? Why/why not?",
  "If you have the choice of giving a transplant to a successful elderly member of the community or a 20- year old drug addict, how do you choose?",
  "If you discovered a classmate cheating, what would you do?",
  "If there were an accident on the highway, would you stop and help the victims, knowing that doing so might lead to a malpractice claim against you?",
  "From an ethical standpoint, regardless of a physician's belief, is the responsibility first and foremost to the patient and his or her needs, or are there circumstances where a physician might legitimately refuse to offer information, refer, or treat a patient?",
  "Do you think a physician should tell a patient he/she has eight months to live?",
  "What do you think of affirmative action?",
  "Would you ever perform an abortion? Under what circumstances?",
  "What test(s) would you give a teenage girl who wants an abortion?",
  "You are caring for a pregnant woman on life support. The child’s life is in jeopardy and delivery is urgently needed, but the husband won’t agree to the procedure. What do you do?",
  "You are a primary care physician who has cared for Mrs. Mitchell for 30+ years. She has been diagnosed with terminal cancer and comes into your office asking for pills she can take when she is ready to die. How do you respond?",
  "Mr. Anderson is dying and in a lot of pain. You want to give him morphine, but the medication will likely lower his blood pressure and hasten his death. You’ve exhausted all your options. Mr. Anderson is still in pain and wants you to end his life. What do you do?",
  "A recently divorced 55-year-old man comes in for a routine visit complaining of insomnia. He requests a sleep aid, asking for a month's supply. On further questioning, he states that he wakes up every morning at four, tired but unable to go back to sleep. He admits that he rarely leaves his house during the day, stating that he has no interest in the activities he used to find enjoyable. What is an appropriate course of action?",
  'A patient tells his family that he would never want to be "kept alive like a vegetable". What is meant by the term "vegetable"?',
  "At what point do you as a physician stop devoting time and resources to a terminally ill patient?",
  "What would you do if you unknowingly resuscitated a DNR patient?",
  "You are an emergency physician caring for a cardiac arrest patient who was brought in by ambulance from a supermarket. As the patient arrives, you receive a call from his daughter stating she has a DNR order and is bringing it immediately. At the same time, the patient’s son arrives in the ED and demands you do everything possible to save his father. What do you do?",
  "A patient who has signed a DNR order has changed her mind and verbally requests you do everything possible to keep her alive. What do you do?",
  "If a patient were brain dead and on life support, how would you make the decision whether or not to discontinue life support?",
  "Would you have “pulled the plug” on Terri Schiavo?",
  "You are caring for a patient who you believe has no chance of meaningful survival. The family requests you do everything you can to save her. You have already put the patient on life support and want to stop with the resuscitation, and believe care is futile. What do you do?",
  "You are taking care of a child who is seriously injured in a car accident with an actively bleeding spleen requiring a blood transfusion. The parents refuse to give consent for the child to receive a transfusion due to their religious beliefs. What do you do?",
  "A pharmacist refused to give birth control pills to a patient with a valid prescription citing ethical beliefs. What do you think about this?",
  "If a thoracic surgeon visited his patients prior to surgery and read from his bible to try and “save” the patient in case any trouble arose, how would you respond?",
  "You walk into the room of a Haitian patient who has had a stroke and is not to eat or drink. The room is filled with family members who are feeding him and none of them speak English. What do you do?",
  "Would you ever lie to a patient?",
  "Describe a time when you thought it was better to be dishonest than tell the truth.",
  "Ms. Chang is an 80 year old woman who was hit by a car and seriously injured. You are the ICU doctor in charge. As you enter the room to tell her the diagnosis, her son stops you and requests you do not tell her because it will be upsetting and prevent her from getting better. He will make all of the medical decisions. What do you do?",
  "Is it acceptable for physicians to modify medical information on insurance forms so companies will be more likely to reimburse patients?",
  "How should be deal with “bad” doctors?",
  "If your attending came into work intoxicated but still performed his work well, would you report him?",
  "You are a first year student. At a party one of your classmates has six beers in one hour and gets very drunk. He behaves similarly at the next party and ends up punching someone. How would you handle this situation?",
  "If you classmate had to miss a class and asked you to sign him in for credit, what would you say to him?",
  "Assume your hospital has regulations about the number of hours you can work per day and you have already worked the maximum number of hours allowed. What would you do if one of your patients coded at the end of your shift?",
  "How would you deal with a patient who is non-compliant?",
  "The state you are practicing in passes a law requiring you to ask the citizenship status of all of your patients and then turn this information into the state at the end of every month. What do you do?",
  "Would you treat an illegal alien?",
  "What do you think about pharmaceuticals directly advertising to physicians? To patients?",
  "A woman with chronic pain and a known narcotic addiction presents in your office requesting medications. She refused to leave until you give her narcotics. What do you do?",
  "How will you handle a patient refusing treatment you have recommended?",
  "A 13 year old girl is diagnosed with Hodgkin’s lymphoma. Her parents refuse what you believe is life-saving treatment for her and decide to travel out of the country for alternative, experimental therapies. What do you do?",
  "During a routine physical examination of a 10-year-old girl you discover unmistakable evidence that she has been physically and sexually abused over a period of time. Both her parents are in the waiting room. How would you respond to this situation?",
  "A seven year old boy has presented to your emergency department for the sixth time this month, and you find out his mother has been neglecting to give him his medications. What do you do?",
  "Should it be legal to force someone, who has shown signs of harming himself or someone else, to take medication?",
  "A 75-year-old woman shows signs of abuse that appear to be inflicted by her husband. As he is her primary caregiver, she feels dependent on him and pleads with you not to say anything to him about it. How would you handle this situation?",
  "You are seeing a patient with kidney failure who refuses dialysis. He later loses consciousness and his family members request that you dialyze him immediately. What do you say and do?",
  "If your sister’s boyfriend came to your practice with an STD, what would you do?",
  "The son of a patient is a physician and calls you to discuss his father’s case. What do you say?",
  "You are caring for an unconscious patient unable to provide consent regarding release of information to his family. His brother calls you to ask how the patient is doing. What do you say?",
  "A 16 year old female, whom you have known and treated in addition to her family for 10+ years, comes to you asking for a birth control prescription. How do you handle this?",
  "A 13 year old boy presents with “leaking” from his penis and you diagnose him with an STD. He begs you not to tell his parents. What do you do beyond prescribing him the correct medication?",
  "A 15 year old girl with a two year old child presents with a broken arm that requires surgery. The 15 year old’s guardian is not available to consent for the surgery. What do you do?",
  "A young mother has just been informed that her 2-year-old son has leukemia. The mother refuses permission to begin chemotherapy and informs the team that their family physician (a naturopath) will follow the child's illness. What should you do?",
  "A three year old female arrives in your emergency department unresponsive with unstable vital signs. There is no adult available to consent for life-saving treatment. What do you do?",
  "As a medical student, you are asked to consent an elderly woman for a hernia repair. She can barely hear and you are fairly confident she did not understand the consent. When you tell the senior resident of your issue, she replies, “Just get it done.” What do you do?",
  "Your patient requires gallbladder surgery and speaks only Thai. You do not speak Thai and there are no interpreters available in the hospital. What do you do?",
  "How do you think we can decrease medical errors?",
  "When should communicable diseases be reported to public health authorities?",
  "Do you think the US should have a national medical errors database? Why or why not?",
  "Medical mistakes are common but not always important. Significant errors leading to morbidity, such as leaving a sponge in the abdomen after surgery, must be disclosed to the patient. Should physicians also disclose less important mistakes, such as a single inconsequential medication error?",
  "What do you think about the current state of malpractice in the US?",
  "You are a fourth year resident performing research and preparing to present your data at an upcoming global conference. Just before you leave, you discover your PI is falsifying data. What do you do?",
  "Many IRBs stipulate that researchers in developing countries must provide the same standard of care for patients as they do in the US. What do you think of this stipulation?",
  "If you could go back in time and ask Henrietta Lacks for permission to use her cells, would you?",
  "Do you think healthcare should be rationed?",
  "What if, while you are spending more time with an elderly terminally ill patient, you spend less time with a sick child, miss a diagnosis, and the child dies?",
  "If you had $100,000 that could support one cancer patient or 100 healthy patients, how would you allocate the funds?",
  'During laparoscopy, a surgeon announces that she intends to proceed to hysterectomy for multiple uterine myomata. The anesthesiologist then declares that he will "wake the patient up" rather than allow the surgeon to proceed, due to lack of consent for the procedure, and questionable medical necessity. Who is in charge when two physicians on the team disagree?',
  "Of a seven year old girl with Down Syndrome, a 35 year old single man with a former drug addiction, and a 51 year old man with a wife and two children, to whom would you give a heart if you only had one?",
  "I am the governor and my wife wants to spend millions of dollars on an anti-meth campaign. What do you think about this use of funds?",
  "What do you think about genetic testing for [insert incurable, life-threatening disease].",
  "How do you feel about stem cell research?",
  "How do you think advancements in gene therapy will affect the future of medicine?",
  "What do you think about cloning?",
  "Would you operate on a HIV+ patient that requires a minor knee operation?",
  "Should we mandate HIV testing?",
  "A patient diagnosed with HIV reveals to their primary care physician they have not disclosed this information to their partner. Discuss the ethical issues involved.",
  "Do you think money is better spent researching HIV/AIDS treatment or cancer treatment?",
  "A 22-year-old woman’s lab tests reveal cryptococcal meningitis, an infection commonly associated with HIV infection. When given the diagnosis, she adamantly refuses to be tested for HIV. Should she be tested anyway by the medical staff?",
  "You are on the organ transplant committee and have to choose between two individuals with liver damage who will die if they don’t receive a new liver. a) A 35 year old mother of three children below the age of 6 and a history of drug abuse  b) A 50 year old man with 20 year old twins and a history of alcohol abuse. This person’s family has given large donations to the school.",
  "A fourth year medical student close to graduation messes up ethically. What do you do to discipline him?",
  "A small town has a sudden surge in DUI and alcohol-related arrests. How do you go about researching the root of this problem?",
  "You are a medical student. One day in the teaching hospital, you see one of your fellow students putting medical equipment from the stock room into their bag. When you ask them about it, they say they only want to practice their clinical skills and not to tell anyone. What would you do?",
  "Organ donation should be an opt-out system rather than an opt-in system in this country. Do you agree or disagree?",
  "What does ‘patient confidentiality’ mean? When would it be appropriate to breach this?",
  "Would you ever prescribe the patient a placebo simply because they wanted treatment?",
  "Would you ever undertreat a patient’s pain if you were concerned of the repercussions or believe the patient might become addicted?",
  "Is it acceptable to perform a procedure that isn’t medically warranted for reasons of defensive medicine?",
  "Would you refer a patient to a physician to return a favor to this physician, even if you believed he was not the best qualified?",
  "Should it be legal for patients to buy organs for transplant if they were not able to receive the organ by waiting their turn in the national database?",
  "The mother of an 18 month old says that she believes that vaccines weaken the immune system and have heard that vaccination can cause autism. The child is unvaccinated. What is your role in this situation? Can parents refuse to immunize their children?",
  "A 23-year-old Navajo man has injured his leg after a fall. His leg appears to be broken. The man requests that you call a medicine man before doing anything further. Should you find a medicine man? Should you proceed with treatment?",
  'You are quite certain a 3 year old child has meningitis. When you discuss the need for a spinal tap and antibiotic treatment, the parents refuse permission, saying, "We\'d prefer to take him home and have our minister pray over him." How would you handle this?',
  'A young accident victim has been in a persistent vegetative state for several months and family members have insisted that "everything possible" be done to keep the patient alive. What are your professional obligations?',
  "40-year-old gay man with AIDS who is intubated with his third bout of pneumocystis pneumonia. His condition is worsening steadily and he has not responded to appropriate antibiotic therapy. The patient's longtime partner, Richard, has a signed durable power of attorney (DPOA) and states that if the patient's condition becomes futile the patient would not want ongoing ventilation. The patient's Roman Catholic parents arrive from Kansas and threaten a lawsuit if the ventilator is withdrawn. What do you do? Who is the legal decision maker here?",
  "Should children be involved in medical decisions even though their parents have final authority to make those decisions?",
  "What happens when an older child disagrees with her parents about a medical treatment?",
  "Would a physician ever be justified in breaking a law requiring mandatory reporting?",
  "What are the ethical concerns when prescribing a medication for a homeless man?",
  "I see there are no doctors in your family. How do you know medicine is the right profession for you?",
  "I see your mother/father is a doctor. Prove to me you’re not going into medicine to please them.",
  "How did your study abroad experience affect you and your studies?",
  "Why did you obtain a graduate degree?",
  "Tell me about your graduate studies.",
  "Why is your research not published?",
  "Tell me about your service trip abroad.",
  "Do you really think a two week service trip made a real difference in the community you served?",
  "How were your clinical experiences abroad compared to your experiences here in terms of the healthcare systems and the outlooks?",
  "Explain your poor grade in [class/semester/year].",
  "There seems to be a mismatch between your GPA and MCAT. Explain.",
  "Tell me about the institutional action against you. How have you changed since then?",
  "As a reapplicant, how have you improved your application?",
  "How do you reconcile your religious faith and interest in science?",
  "How do you feel your religious beliefs will influence your patient care?",
  "Questions to Ask Yourself or Your Interviewer (Most of them from here)",
  "Are there any special programs for which this medical school is noted?",
  "Describe this school's curriculum in the pre-clinical and clinical years. Are there any innovations, like Problem-Based Learning?",
  "Are there opportunities for students to design, conduct, and publish their own research?",
  "Is there a note-taking service? If so, is it University-run or student-run?",
  "Is there flexibility in the coursework (the number of electives) and the timing of the courses (accelerating, decelerating, and time off) during the pre-clinical and clinical years?",
  "Was this medical school, or any of its clinical departments, been on probation or had its accreditation revoked?",
  "How do students from this medical school perform on the National Board Examinations? How does the school assist students who do not pass?",
  "How are students evaluated academically? How are clinical evaluations performed?",
  "Is there a formal mechanism in place for students to evaluate their professors and attending physicians? What changes have been made recently as a result of this feedback?",
  "What kind of academic, personal, financial, and career counseling is available to students? Are these services also offered to their spouses and dependents/children?",
  "Is there a mentor/advisor system? Who are the advisors—faculty members, other students, or both?",
  "How diverse is the student body? Are there support services or organizations for ethnic minorities and women?",
  "Tell me about the library and extracurricular facilities (i.e., housing and athletic/recreational facilities).",
  "Are there computer facilities available to students? Are they integrated into the curriculum/learning?",
  "What type of clinical sites—ambulatory, private preceptors, private hospitals, rural settings— are available or required for clerkships? Does this school allow for students to do rotations at other institutions or internationally?",
  "Is a car necessary for clinical rotations? Is parking a problem? Do you like rotating in different places or do you find it difficult to commute/travel?",
  "What is the current tuition and fees? Is this expected to increase yearly? If so, at what rate?",
  "Are there stable levels of federal financial aid and substantial amounts of university/medical school endowment aid available to students?",
  'Are there students who have an "unmet need" factor in their budget? If so, where do these students come up with the extra funds?',
  "Are spouses and dependents/children covered in a student's budget?",
  "Is someone available to assist students with budgeting and financial planning?",
  "Does this school provide guidance to its students, and to its graduates/alumni, on debt management?",
  "What medical school committees (e.g., curriculum committee) have student representation?",
  "Are students involved in (required or voluntary) community service?",
  "How active is the Student Council/Government? Are there other student organizations?",
  "Is there an established protocol for dealing with student exposure to infectious diseases? Is disability insurance provided to cover this exposure?",
  "Does this school provide, or does the student pay for, vaccinations against Hepatitis B or prophylactic AZT treatment in case of a needle-stick or accident?",
  "Is there a school Honor Code? Is there a grievance process/procedure? Are the students involved?",
  "May I see a list of residency programs to which this school's recent graduates were accepted?",
  "Does this school have strengths in the type of medicine (primary versus specialized care, urban versus rural practice environment, academic medicine versus private practice) that I will want to practice?",
  "Would I be happy at this school (for at least the next four years)?",
  "How much time do you get off to study for Step 1 and interview for residencies?",
  "What kind of study facilities are available for medical students?",
  "How common is it that students stay at this school for residency?",
  'What is third year like and how is it structured? How are rotations structured? What is your role on the wards? Do you have a clear role? Do you “get your hands dirty" or is it a lot of shadowing?',
  "How are clinical evaluations determined? Do you find they are fair and transparent?",
  "What is one thing you would change about this school?",
  "How would you describe the student body?",
  "Why do you love it here?",
  "What do you like most and what do you like least about this medical school?",
  "Is there anything else you think I should know about [school]?",
  "Do you have any tips for me as I move through my medical education?",
  "How have you balanced clinical work and research?",
  "How did you choose your specialty?",
  "Do you expect any changes to the program in the next few years?",
  "What is the most exciting research going on at the school this year?",
  "What kind of electronic journal access is available to students? Electronic textbooks? UpToDate?",
  "What kind of things do people do for fun here?",
  "Is anatomy taught with a cadaver lab, prosections, a computer lab, or some combination of the three?",
  "Is there ample opportunity to do away rotations before applying to residencies?"]

export const law_lst = [
"How did you select your undergraduate university?",
"Think back on your undergraduate experience at Slippery Rock University. What would you change about it?",
"If you were in charge of Slippery Rock University, what would you change that would impact the undergraduate experience as it pertains to advancement to law school?",
"What undergraduate courses did you enjoy most? Least?",
"Why did you choose your undergraduate major?",
"What extracurricular activities were you involved in during your undergraduate years?",
"What was your toughest class? Why? What skills have you developed outside the classroom?",
"Describe your best college professor. What made them unique? What has been your favorite course and why?",
"How have you benefited from your undergraduate education?",
"How many hours a week did you study?",
"How has your undergraduate experience made you a better person?",
"What subjects are you now studying? Discuss.",
"Why did you drop, fail, or get a particular grade in a certain class?",
"Outline your study techniques.",
"Do your grades accurately reflect your ability?",
"Why do you want to be a lawyer?",
"What stimulated your interest in law?",
"If you want to “help people”, why not medicine? Social Work? Teaching?",
"What experience crystallized your decision to become a lawyer?",
"Which area of law are you most interested in?",
"What kind of experiences do you have in the law field?",
"How do you know you will make a good lawyer?",
"Why do you think so many people want to be lawyers?",
"What steps have you taken to familiarize yourself with the daily activities of a lawyer?",
"How did you investigate a career in law?",
"How do your parents and friends feel about your career decision? How have they influenced you in this decision?",
"What contribution to law can you make?",
"What type of lawyer would you like to be? Why?",
"o you have family members who are lawyers? What do they think of the field? How have their lives changed or the past few years with the changes in law? Do you want to follow in their footsteps?",
"What are your specific goals in law?",
"What do you look for when choosing a lawyer?",
"What are the negative aspects of law from a professional standpoint?",
"What do you think are a lawyer’s social responsibilities? How do you plan to personally contribute to society as lawyer? ",
"Do you think the public views the legal profession?",
"Why you select this school and why do you want to attend?",
"Are you satisfied with your scores?",
"Why should we choose you?",
"What do you think make you a good candidate for law school?",
"Discuss a book that you recently read for pleasure. Why does this book interest you?",
"What negative things have you heard about the area you want to go into, and how do you feel about them?",
"How have your personal and volunteer experiences strengthened your goal to become a lawyer?",
"What are the most important rewards you expect from a legal career?",
"Would you prefer to work on one big case for an entire year, or 12 diff time?",
"How did you decide to apply to our law school?",
"Why did you choose our specific program?",
"How are you a match for our law school?",
"What other law schools have you applied to?",
"Explain the poor grades on your transcript/low LSAT scores.",
"Would you go to our program if I gave you an acceptance letter?",
"What is your biggest concern about entering law school?",
"If you are accepted to multiple schools, how will you make the decision?",
"Why should we offer you a place?",
"How did you prepare for the LSAT?",
"How will you pay for your law school education?",
"Do you consider yourself a competitive applicant to this school?",
"There are 1,000 applicants as qualified as you are. Why should we choose you?",
"What do you have to offer to our school?",
"What aspects of your life’s experiences do",
"What do you hope to gain during your law education?",
"What problems do you expect to arise during law schhool?",
"What are your positive qualities and what are your shortcomings?",
"What is your relationship with your family?",
"Describe your personality.",
"What is the best thing that has happened to you?",
"If your best friend were asked to describe you, what would they say?",
"What are three things that you would change about yourself?",
"Name something you are most proud of.",
"Which family member has influenced your life so far and why.",
"Describe yourself in terms of your greatest strengths and weaknesses.",
"When you need counseling for personal problems, with whom do you talk?",
"Describe your childhood.",
"Do you plan to continue your hobbies through law school?",
"Outside of your family, who is your biggest role model?",
"Do you like being alone? When you are alone, what do you do?",
"Tell me about your family. How do they feel about your decision to attend law school?",
"If you had one day to do anything, what would you do?",
"Who knows you best in this world? How would that person describe you?",
"Who are your heroes?",
"What additional activities have you pursued?",
"What is the funniest thing that has ever happened to you?",
"What newspapers/journals do you read on a regular basis?",
"Describe any travel experiences?",
"If you could invite three living persons to dinner on success",
"What was the last movie you saw? What did you think of it?",
"What current events were reported on last night’s news?",
"What person, past or present, would you most like to meet?",
"If you could be any character in history, who would you be and why?",
"What do you do in your spare time?",
"What is your main interest outside of law?",
"How do you handle stress?",
"What has been your most stressful experience to date?",
"How do you think your personal background will affect your practice?",
"What is the biggest mistake you have ever made? What did you learn from?",
"Have you always put forth your best effort in every situation?",
"Tell me about something you know a lot about.",
"What do you care about?",
"What accomplishments are you most proud of?",
"What motivates you to do your best? How do yo",
"Have you taken advantage of the opportunities available to you on campus to become involved in a com",
"people-oriented activity?",
"Describe a time when you had to take a leadership role in coaching or instructing someone. What were you providing instructions on? How did you assess the learner's comprehension of the problem? What feedback di you provide?",
"In your view, how does leadership fit into the role of a lawyer?",
"What is your strongest leadership skill and how will it assist you in this profession?",
"What would you do if a client didn’t like you?",
"What experience have you had in working with others as part of a team?",
"Tell me about a time when you had to deal with situation? What was the outcome?",
"Describe a face-to-face meeting in which you had to influence a highly emotional in did you use? What happened?",
"Sometimes it’s important to disagree you were willing to disagree with another person in order to build a positive outcome.",
"Tell me about a situation in which you felt you acted too quickly and later regretted it. What caused it? ",
"Do you have an alternative career plan? ",
"If the law field didn’t exist, what would you do with your life?",
"What is your “cause”? What are you passionate about?"
]